Algoritmo "Correntista"
//1)Crie um algoritmo que lê o nome de um correntista,
// sua agência e conta. Exiba esses dados na tela
Var
correntista: caracter
agencia, conta: inteiro


Inicio
Escreval("Digite o nome de um correntista: ")
Leia(correntista)
Escreval("Digite o número da agência: ")
Leia(agencia)
Escreval("Digite o número da conta: ")
Leia(conta)

Escreval("o nome do correntista é " + correntista)
Escreval("sua agência é ", agencia)
Escreval("sua conta é ", conta)

Fimalgoritmo